# OpenAI設定
openai:
  api_key: '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'
  embedding_model: 'text-embedding-3-large'
  chat_model: 'gpt-4o-mini'

# Google設定
google:
  service_account_file: '/Users/aokiyuto/Documents/secret.json'

# Google Drive設定
google_drive:
  folder_id: '1-84UXPCVDXj-ca0xLR0bKrzB-6Oqe65m'