# GCS設定
gcs:
  bucket_name: 'chatbot-input-documents'
  document_vectors_file: 'document_vectors.json'

# OpenAI設定
openai:
  api_key: 'your-openai-api-key'
  embedding_model: 'text-embedding-3-large'
  chat_model: 'gpt-4o-mini'

# Slack設定
slack:
  bot_token: 'your-slack-bot-token'
  app_token: 'your-slack-app-token'
  signing_secret: 'your-slack-signing-secret'
  allowed_channels: ['CHANNEL_ID_1', 'CHANNEL_ID_2', 'CHANNEL_ID_3']

# Google設定
google:
  service_account_file: '/Users/aokiyuto/Documents/secret.json'

# Google Drive設定
google_drive:
  folder_id: 'your-folder-id'

# システムプロンプト
system_prompt: '以下の情報のみを使用して回答してください。'